# Generated by Antigravity for eu-filings-mcp-server
# This Dockerfile sets up the MCP server to run via SSE on port 8017

FROM node:20-slim
 
WORKDIR /app
 
COPY package*.json ./
 
RUN npm install --production
 
COPY . .
 
EXPOSE 8017
 
ENTRYPOINT ["node", "src/index.js"]
CMD ["--sse", "--host=0.0.0.0", "--port=8017"]