# Generated by Antigravity for eu-filings-mcp-server
# This Dockerfile sets up the MCP server to run via SSE on port 8017

FROM node:18-slim

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install --production

# Bundle app source
COPY . .

# Expose the SSE port
EXPOSE 8017

# Using SSE transport on port 8017 by default (can be overridden)
ENTRYPOINT ["node", "src/index.js"]
CMD ["--sse", "--host=0.0.0.0", "--port=8017"]
